name: CI

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  nocommit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      - uses: nobssoftware/nocommit@5c3cf9519fe40b80b0954d254085b67b532a5dc3

  nix-flake-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      - uses: cachix/install-nix-action@4e002c8ec80594ecd40e759629461e26c8abed15
      - uses: determinatesystems/magic-nix-cache-action@565684385bcd71bad329742eefe8d12f2e765b39
      - run: nix run .#nix-flake-check-changed

  nix-flake-health:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      - uses: cachix/install-nix-action@4e002c8ec80594ecd40e759629461e26c8abed15
      - uses: determinatesystems/magic-nix-cache-action@565684385bcd71bad329742eefe8d12f2e765b39
      - run: nix flake show
      - run: nix flake lock --no-update-lock-file
      - run: nix flake check --no-build
